In [1]:
from sklearn import datasets

In [6]:
import numpy as np

In [2]:
iris = datasets.load_iris()

In [3]:
x = iris.data[:, ]

In [4]:
y= iris.target

In [7]:
print('class labels:', np.unique(y))

class labels: [0 1 2]


In [8]:
from sklearn.cross_validation import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state = 1, test_size = 0.3, stratify = y)

In [11]:
print('Label count in y:',np.bincount(y))

Label count in y: [50 50 50]


In [12]:
print('Label count in y_train:', np.bincount(y_train))

Label count in y_train: [35 35 35]


In [13]:
from sklearn.preprocessing import StandardScaler

In [15]:
sc = StandardScaler()

In [17]:
sc.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [18]:
X_train_std = sc.transform(X_train)

In [19]:
X_test_std = sc.transform(X_test)

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
lr = LogisticRegression(C=100.0, random_state=1)

In [22]:
lr.fit(X_train_std, y_train)

LogisticRegression(C=100.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=1, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [25]:
lr.predict_proba(X_test_std[:3, :])

array([[9.77284124e-06, 8.17997173e-02, 9.18190510e-01],
       [9.80969119e-01, 1.90308812e-02, 2.23010767e-14],
       [8.84888067e-01, 1.15111933e-01, 2.15233379e-14]])

In [26]:
lr.predict(X_test_std[:3,:])

array([2, 0, 0])

In [27]:
"""Note: To predict the class label of a single sample, scikit-learn expects a 2D array of input.
    We have to convert a single row slice into such a format first.
"""
lr.predict(X_test_std[0,:].reshape(1, -1))

array([2])